### ISSUE TITLE
java.lang.IllegalStateException: Service method not found when using Koin

### ISSUE THREAD

**Issue by CaptnBlubber** [Tinder/Scarlet#28]
I am trying to use Scarlet with [Koin](https://github.com/InsertKoinIO/koin) but everytime I acces the Service instance from the dependency graph, Scarlet throws an `java.lang.IllegalStateException: Service method not found` Exception.

Here is how the Dependency definition looks like
```
val networkingModule = module {
    single { createOkHttpClient() }
    single { createScarlet(get(), "ws://demos.kaazing.com/echo") }
    single { createEchoService(get()) }
}


fun createOkHttpClient(): OkHttpClient = OkHttpClient.Builder()
        .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
        .build()

fun createScarlet(client: OkHttpClient, url: String) = Scarlet.Builder()
        .webSocketFactory(client.newWebSocketFactory(url))
        .addMessageAdapterFactory(MoshiMessageAdapter.Factory())
        .addStreamAdapterFactory(CoroutinesStreamAdapterFactory())
        .build()

fun createEchoService(scarlet: Scarlet): EchoService = scarlet.create()
```

And this is how you would end up calling it (in this example Activity):

```
class MainActivity : AppCompatActivity() {

    val service: EchoService by inject() //lazy!

    override fun onCreate(savedInstanceState: Bundle?) {
        ...
        service.observeEvents()
    }
}
```

Injecting the Scarlet Instance and creating the service in the activity however would work:
```
class MainActivity : AppCompatActivity() {

    val scarlet: Scarlet by inject()

    override fun onCreate(savedInstanceState: Bundle?) {
        ...
        val service: EchoService = scarlet.create()
        service.observeEvents()
    }
}
```
The only Problem with the workaround is that I would need to create new instances of the service everywhere I need it. Of course I could setup a holder pattern or something but that would defeat the purpose of using DI.

Here is the full stacktrace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sample.scarlet/com.sample.scarlet.MainActivity}: java.lang.IllegalStateException: Service method not found
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Service method not found
        at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor.execute(ServiceMethodExecutor.kt:18)
        at com.tinder.scarlet.internal.Service.execute(Service.kt:18)
        at com.tinder.scarlet.Scarlet$createInvocationHandler$1.invoke(Scarlet.kt:123)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy2.toString(Unknown Source)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at org.koin.core.instance.InstanceRegistry$proceedResolution$$inlined$synchronized$lambda$1$1.invoke(InstanceRegistry.kt:112)
        at org.koin.core.instance.InstanceRegistry$proceedResolution$$inlined$synchronized$lambda$1$1.invoke(InstanceRegistry.kt:36)
        at org.koin.core.stack.ResolutionStack.resolve(ResolutionStack.kt:44)
        at org.koin.core.instance.InstanceRegistry$proceedResolution$$inlined$synchronized$lambda$1.invoke(InstanceRegistry.kt:105)
        at org.koin.core.instance.InstanceRegistry$proceedResolution$$inlined$synchronized$lambda$1.invoke(InstanceRegistry.kt:36)
        at org.koin.core.time.DurationKt.measureDuration(Duration.kt:8)
        at org.koin.core.instance.InstanceRegistry.proceedResolution(InstanceRegistry.kt:84)
        at org.koin.core.instance.InstanceRegistry.resolve(InstanceRegistry.kt:63)
        at org.koin.core.instance.InstanceRegistry.resolve$default(InstanceRegistry.kt:48)
        at com.sample.scarlet.MainActivity$$special$$inlined$inject$1.invoke(ComponentCallbacksExt.kt:148)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.sample.scarlet.MainActivity.getService(Unknown Source:7)
        at com.sample.scarlet.MainActivity.onCreate(MainActivity.kt:19)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by mhelder** [comment]
Just wanted to add that we ran into the same problem, but _only_ with Koin 1.0(+). We're currently still using Koin 0.9.2, which does work just fine (0.9.3 only had build chain changes, so would probably work fine too).

In theory it could also be a problem in Koin, or the Kotlin stdlib, but the latter seems unlikely because we have recently updated our project to Kotlin 1.2.71 without a hitch...

**Comment by neilg** [comment]
It looks to me like Koin is calling toString() on the service proxy created by Scarlet.
`
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy2.toString(Unknown Source)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at org.koin.core.instance.InstanceRegistry$proceedResolution$$inlined$synchronized$lambda$1$1.invoke(InstanceRegistry.kt:112)
`

I've just run into a similar problem with a framework calling hashCode() on the service proxy. The ServiceMethodExecutor doesn't support the methods inherited from java.lang.Object.

**Comment by neilg** [comment]
I think it should be straightforward to fix this. If I have time, I'll have a go over the weekend.

**Comment by neilg** [comment]
I've found a workaround:
replace
```
val service = scarlet.create<TheServiceInterface>()
```
with
```
val service = object : TheServiceInterface by scarlet.create(){}
```
